### PR TITLE
improved and extended Dutch translation

### PR DESCRIPTION
**Pull request by PanderMusubi**
Can changes of src/qt/locale/bitcoin_nl.ts also be propagated to upstream? (Follow up question, how is synchronisation with upstream done at the moment?)

### CODE REVIEW

**Comment by mjmacleod** [comment]
Thanks for the pull request.

Translations are done by community via our translation portal http://translate.gulden.com/ and merged back into the code base via an automatic update script.

I ideally can't/won't merge direct translation changes like this as it interferes with this process, translations made via the portal allow the opportunity for other native language speakers to look at them and to vote which they feel is more accurate..

You'll want to look at 2.0_development branch as this is where the latest translations are - the master branch is the old 1.6.4 branch which is set to be deprecated at the end of this month and there are substantial changes between the two branches.

**Comment by PanderMusubi** [comment]
Adding translations there now. Please, add that URL also to development documentation so others will also go there directly.

Additional question, can the translation of the main website also be done in there?

**Comment by mjmacleod** [comment]
It is already mentioned here https://github.com/Gulden/gulden-official/blob/master/CONTRIBUTING.md 

As we are in the final phases of a major release (1 full year of development) this month I won't have time to look at documentation right now, but I'll be happy to look at such things post 2.0 release.

**Comment by PanderMusubi** [comment]
(The Dutch translations really need a lot of work. Many times they have been made a too literal translation from English to Dutch. Contributing via that link as we speak.)

**Comment by mjmacleod** [comment]
I'd recommend joining #translators on our slack channel as well for best communication with other translators, opinions on translations often differ so it is best to discuss when in doubt, however all translation contributions are of course very welcome.

**Pull request closed without merging**
